name: $(BuildDefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)
pool: Hosted Ubuntu 1604
resources:
  repositories:
    - repository: templates
      type: git
      name: Glasswall.Pipelines.Templates
    - repository: this
      type: git
      name: Glasswall.SRE.Destroyer
      trigger:
        branches:
          - master
jobs:
  - template: Python/template-ci.yml@templates
