logging_config:
  version: 1
  formatters:
    default:
      format: "%(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default
      stream: ext://sys.stdout
  root:
    level: DEBUG
    handlers: [console]

access:
  access_token: access-token
  organisation: glasswall
  project: Glasswall Cloud
  email: apotter-dixon@glasswallsolutions.com
environments:
  - dev
  - qa
  - pent
  - perf
  - stage

deployments:
  - stage: deploy_init_infrastructure
    pipelines:
      - Platform.Infrastructure
  - stage: deploy_main_infrastructure
    pipelines:
      - Platform.Kubernetes
      - Platform.Logging
      - Platform.Postfix
      - Platform.Prometheus
      - Platform.Prometheus.Exporters
  - stage: deploy_init_services
    pipelines:
      - FileTrust.Common
      - Glasswall.IdentityServer4
      - FileTrust.TenancyManagement.Api
      - FileTrust.Api
      - FileTrust.StorageAccessService.Api
      - FileTrust.TransactionReporter.Api.Sql
      - FileTrust.TransactionReporter.Api
  - stage: deploy_main_services
    pipelines:
      # * Defines every other pipeline that was missed.
      - "*"
