logging_config:
  version: 1
  formatters:
    default:
      format: "%(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default
      stream: ext://sys.stdout
  root:
    level: DEBUG
    handlers: [console]

access:
  access_token: 67sc3y3bp37wumt2hd33bmokom5mxa3xkw3ed5y53q3kzbqnuquq
  organisation: glasswall
  project: Glasswall Cloud
  email: apotter-dixon@glasswallsolutions.com
environments:
  - dev
  - qa
  - pent
  - perf
  - stage

deployments:
  - stage: deploy_init_infrastructure
    releases:
      - name: FileTrust.Blackhole
  - stage: deploy_next_infra
    releases:
      - name: FileTrust.TenantCreation
