logging_config:
  version: 1
  formatters:
    default:
      format: "%(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default
      stream: ext://sys.stdout
  root:
    level: DEBUG
    handlers: [console]

***REMOVED***
  access_token: 67sc3y3bp37wumt2hd33bmokom5mxa3xkw3ed5y53q3kzbqnuquq
***REMOVED***
***REMOVED***
***REMOVED***
environments:
  - dev
  - qa
  - pent
  - perf
  - stage

***REMOVED***
***REMOVED***
***REMOVED***
      - name: FileTrust.Blackhole
  - stage: deploy_next_infra
***REMOVED***
***REMOVED***
